### ISSUE TITLE
Not compatible with symfony/process:^5.0

### ISSUE THREAD

**Issue by willemstuursma** [PayU-EMEA/apple-pay#13]
The package is not compatible with `symfony/process:^5.0`. 

No need to work on it yourself, but I may open a PR one day to sort it out and would like it to be tracked here.

**Comment by trydocatch** [comment]
It looks like symfony/process 5.0 requires min PHP version 7.2.5. So for who's using older versions of PHP,  this wouldn't work.

**Comment by willemstuursma** [comment]
For PCI-DSS environments I guess PHP 7.2 is the minimum, as it is the lowest PHP version that still gets security updates.

**Comment by drealecs** [comment]
I think what @willemstuursma intended here would be to change in the composer.json require:
```
"symfony/process": "^3.4|^4.0"
```
with
```
"symfony/process": "^3.4|^4.0|^5.0"
```
That would still work with older PHP versions that would use older symfony/process versions.

Just to have it documented here, the main change would be in `OpenSslService.php` where the Process ctor now requires an array as commandline parameter.
Array version should also work for older mentioned versions, from what I know.

**Comment by willemstuursma** [comment]
Cheers @drealecs.
