### ISSUE TITLE
Private key

### ISSUE THREAD

**Issue by webdesign7** [PayU-EMEA/apple-pay#19]
Hello, 

How / where  can I get the private key , our payment provider seems to generate only a CSR which then we upload to Apple 

Please advice
Thanks

**Comment by NDQuattro** [comment]
Hey. Contact your PSP for that or make your own CSR and exchange it for the payment processing cert.
You have any success?

**Comment by trydocatch** [comment]
If you have a "payment provider", why do you need the private key? The decoding should be performed by the PSP so only they need the private key.

**Comment by bratpidd** [comment]
Maybe in the end this will help someone. MacOS tricks.
1. Private key is taken from Apple Pay **Payment Processing** Certificate, not the Merchant Identity one.
3. On MacOS after executing `openssl pkcs12 -in <your_cert>.p12 -out private_key.pem -nocerts` you will get a file with a section "-----BEGIN PRIVATE KEY-----" etc. This is not what we want, we want a block "-----BEGIN EC PRIVATE KEY-----"
4. To finally see the EC private key, run `openssl ec -in private_key.pem -text`
5. The value is our working private key. Copy it and make it one-line in the code.

**Comment by JeanCarlosDev17** [comment]
> Maybe in the end this will help someone. MacOS tricks.
> 
> 1. Private key is taken from Apple Pay **Payment Processing** Certificate, not the Merchant Identity one.
> 2. On MacOS after executing `openssl pkcs12 -in <your_cert>.p12 -out private_key.pem -nocerts` you will get a file with a section "-----BEGIN PRIVATE KEY-----" etc. This is not what we want, we want a block "-----BEGIN EC PRIVATE KEY-----"
> 3. To finally see the EC private key, run `openssl ec -in private_key.pem -text`
> 4. The value is our working private key. Copy it and make it one-line in the code.

you try with Apple Pay Payment Processing Certificate and work?
